### ISSUE TITLE
Object [object Object] has no method 'split'

### ISSUE THREAD

**Issue by kachkaev** [apollostack/meteor-starter-kit#12]
Looks like a minor update in apollo server (or another package?) broke the BC. There's now this error on the page after a user has logged in:

![apollo client error](https://cloud.githubusercontent.com/assets/608862/16333239/2a6c8fa2-39f2-11e6-9af2-e1782cea2fb2.png)

This happens both after installing dependencies 'as is' and after trying to update everything to the latest versions. The same request on `/graphql` page works OK.

**Comment by kachkaev** [comment]
![](http://vignette4.wikia.nocookie.net/jackinthebox/images/2/2f/Tumbleweed.gif/revision/latest?cb=20140411060510)

**Comment by fkhoda** [comment]
Same for me. Did you manage to fix it?

**Comment by kachkaev** [comment]
Nope. Spent 2 hrs and gave up :–) This seems to be an issue in `apollo-server` (just a guess).

**Comment by fkhoda** [comment]
I'm guessing the same, since it is coming from the remote endpoint.

**Comment by brunolemos** [comment]
@stubailo could you help us? it doesn't work at all

**Comment by stubailo** [comment]
Maybe @helfer can take a look? If not I can check it out on Tuesday. Has anyone tracked down the cause?

**Comment by helfer** [comment]
Is it possible that this has to do with the fact that Meteor still uses Node 0.12 or something? I had something similar with Array.concat the other day.

Can you do me a favor and get the stack trace of the the error on the server by passing this to apolloServer:
```
printError: (err) => { console.log(err.originalError); return err.originalError; }

**Comment by brunolemos** [comment]
@helfer nothing got printed on the server, but this on the client: 
```
POST http://localhost:3000/graphql 400 (Bad Request)
fetchFromRemoteEndpoint @ networkInterface.js:39
(anonymous function) @ dynamics_browser.js:51````

**Comment by brunolemos** [comment]
Wow can't believe meteor still uses node v0.10.45 😮

**Comment by kachkaev** [comment]
@brunolemos true. This should change in the next release though: https://github.com/meteor/meteor/pull/7218 :–)

**Comment by helfer** [comment]
@brunolemos Oh, my bad, the function should be called `formatError`, not `printError`. Can you try it again?

**Comment by brunolemos** [comment]
@helfer `undefined` 😛

But I got to print the stack trace, this may help:

```
TypeError: Object [object Object] has no method 'split'
    at highlightSourceAtLocation (node_modules/graphql/error/syntaxError.js:42:27)
    at syntaxError (node_modules/graphql/error/syntaxError.js:28:155)
    at unexpected (node_modules/graphql/language/parser.js:971:33)
    at parseDefinition (node_modules/graphql/language/parser.js:126:9)
    at parseDocument (node_modules/graphql/language/parser.js:80:22)
    at parse (node_modules/graphql/language/parser.js:42:10)
    at Promise.then.then.errors (node_modules/express-widgetizer/dist/index.js:183:42)
    at /Users/brunolemos/.meteor/packages/promise/.0.7.2_1.1r7p0rv++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39
```

**Comment by helfer** [comment]
Can you try the same after updating to the beta version of Meteor 1.4 in your app? I'm curious if that will solve it. https://forums.meteor.com/t/announcing-meteor-1-3-4-1-and-1-4-beta-1/25460/1

**Comment by brunolemos** [comment]
@helfer unfortunately I was unable to run it because of meteor/meteor#7297

**Comment by helfer** [comment]
Ugh. Ok, let's see what we can do without that update...

One thing that that stack trace already seems to indicate is that there's a syntax error in the query, because the `split` error is thrown inside graphql-js' syntaxError function. Do you know what query that component is trying to run?

**Comment by brunolemos** [comment]
@helfer debugging it.

The query is:
```
query getUserData ($id: String!) {
  user(id: $id) {
    emails {
      address
      verified
    }
    username
    randomString
  }
}
```

The split error is because the syntaxError is expecting a string on source.body but receiving an object `{ kind: 'Document', definitions: [ [Object] ] }`.

Not sure what's the cause.

I noticed that there is a difference between the payload data sent by the app client and the one by graphiql.

On Meteor Apollo boilerplate POST payload (`query` and `variables` are objects):
```
{
    operationName: "getUserData",
    query: {kind: "Document", definitions: [{kind: "OperationDefinition", operation: "query",…}]},
    variables: {id: "b65LgAz6dKYLXwHnH"}
}
```

GraphiQL POST payload (`query` and `variables` are strings):
```
{
    operationName: "getUserData"
    query: "query getUserData (...) {...}",
    variables: '{↵  "id": "b65LgAz6dKYLXwHnH"↵}'
}
```

Is that expected?

**Comment by helfer** [comment]
Ah, I see. I think this is due to a recent change that we made in Apollo Client. Can you confirm, @Poincare ?

**Comment by brunolemos** [comment]
It works after downgrading apollo-client to v0.3.12!

**Comment by helfer** [comment]
You could probably also fix it by changing the NetworkInterface to print the AST before calling fetch. I think Apollo Client exports a `print` function that can be used for this.

**Comment by stubailo** [comment]
Yeah I think this is because of an accidental breaking change where we pass the AST instead of query string to the network interface.

**Comment by helfer** [comment]
The change itself wasn't accidental though, I believe, because the AST is needed for query mangling. The alternative would be to print it, and then parse it again in the network interface.

**Comment by jschlieber** [comment]
I just cloned the [meteor-integration](https://github.com/apollostack/meteor-integration) project into my local `packages` folder of the meteor-starter-kit and voila, the error is gone...
Any ideas why?

**Comment by stubailo** [comment]
I think we just had to republish the meteor integration package. Now a fresh clone runs correctly for me.

**Comment by payner35** [comment]
same problem here...

a quick Meteor Update solved this..

apollo  upgraded from 0.0.2 to 0.0.3
