### ISSUE TITLE
Variable \"$id\" of required type \"String!\" was not provided.

### ISSUE THREAD

**Issue by SachaG** [apollostack/meteor-starter-kit#2]
When I run the app and click "refetch!" this is what I see: 

```

{
  "loading": false,
  "result": null,
  "errors": [
    {
      "message": "Variable \"$id\" of required type \"String!\" was not provided.",
      "locations": [
        {
          "line": 2,
          "column": 32
        }
      ]
    }
  ]
}
```

I'm coming at this with zero GraphQL experience so I don't even know if that's what the app is supposed to do or not… But I'm guessing not?

**Comment by stubailo** [comment]
Fixed. This is where the bug from refetch is coming from: apollostack/apollo-client#138
