### ISSUE TITLE
Error when using latest apollo-server

### ISSUE THREAD

**Issue by lorensr** [apollostack/meteor-starter-kit#24]
On master, do `npm i --save apollo-server@*`, and then you get:

```sh
$ meteor
[[[[[ ~/gh/meteor-starter-kit ]]]]]           

=> Started proxy.                             
=> Started MongoDB.                           
W20160816-23:27:47.322(-4)? (STDERR)                                               
W20160816-23:27:47.409(-4)? (STDERR) /Users/me/gh/meteor-starter-kit/.meteor/local/build/programs/server/packages/modules.js:7206
W20160816-23:27:47.409(-4)? (STDERR) const graphql_1 = require('graphql');         
W20160816-23:27:47.410(-4)? (STDERR) ^^^^^                                         
W20160816-23:27:47.410(-4)? (STDERR) SyntaxError: Use of const in strict mode.     
W20160816-23:27:47.410(-4)? (STDERR)     at /Users/me/gh/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:292:30
W20160816-23:27:47.410(-4)? (STDERR)     at Array.forEach (native)                 
W20160816-23:27:47.411(-4)? (STDERR)     at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.3.4_1.1v15hy2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160816-23:27:47.411(-4)? (STDERR)     at /Users/me/gh/meteor-starter-kit/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8 
```

![image](https://cloud.githubusercontent.com/assets/251288/17723595/364ce0d8-6409-11e6-975d-4e1a593eb400.png)

Usually this error would mean that you're using a version of node that doesn't support ecmascript. This is meteor `1.3.4_1`

**Comment by lorensr** [comment]
https://github.com/apollostack/meteor-integration/pull/26#issuecomment-240305261

**Comment by smooJitter** [comment]
I saw this a few weeks back.  I began working on a few other things.  I'm not sure if I understand, has this been resolved.  I thought my problem was caused by switching to meteor 1.4

**Comment by lorensr** [comment]
This might be due `apollo-server` not prepublish transpiling to support node `0.10`? Will try meteor 1.4. If it ever finishes downloading 😜

**Comment by jangerhofer** [comment]
OK, I've got everything but the UI working [here](https://github.com/jangerhofer/meteor-starter-kit/tree/apolloServer_0.2).  *Note: you will need to checkout [my PR on the meteor-integration package](https://github.com/apollostack/meteor-integration/pull/26) into the `packages` folder.*  

The login form loads, but it throws an error: `getNodeFromInstance: Invalid argument.` that stems from the `std:accounts-ui` package which seems to be outdated.

**Comment by lorensr** [comment]
1.4 gets you past this error, so I filed under https://github.com/apollostack/apollo-server/issues/99
