### ISSUE TITLE
Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.

### ISSUE THREAD

**Issue by markoshust** [apollostack/meteor-starter-kit#27]
This repo doesn't work. Receiving this error when launching http://localhost:3000

```
invariant.js:38 Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.
```

I'm seeing the login screen, but the Register button is grayed out.

**Comment by hector-valdivia** [comment]
For de master branch the problem is de version of apollo-server, it works good wit apollo-server@0.1.5, if you want to use the newer apollo-server@0.2.5 install:
`apollo@0.1.0-beta_2`

**Comment by rdickert** [comment]
This appears to be a dupe of #16.

**Comment by markoshust** [comment]
Yes it is, thanks
