### ISSUE TITLE
Access is denied IE9

### ISSUE THREAD

**Issue by bompi88** [apollostack/meteor-starter-kit#29]
While trying the app with IE9, I get the following error in the UI:

```json
{
    "message": "Access is denied.\r\n",
    "description": "Access is denied.\r\n",
    "number": -2147024891
}
```

Any suggestions why this is happening?

**Comment by helfer** [comment]
@bompi88 Were you able to solve this somehow? I haven't seen this error before, and it's a bit hard to debug without more context...

**Comment by bompi88** [comment]
Sorry I forgot, Yes I have. This error message has nothing to do with this repo at all. I'll close it.

I was testing with VirtualBox, and `ROOT_URL` was not set properly. I modified the `ROOT_URL` to point to the host IP, and all worked well.
