### ISSUE TITLE
context is undefined

### ISSUE THREAD

**Issue by sabativi** [apollostack/meteor-starter-kit#37]
When starting with this repo and testing a query in graphiql, there is a problem as context is undefined.
Am i missing something ?
Thanks

```
async user(root, args, context) {
      // Only return the current user, for security
      if (context.userId === args.id) {
        return await Meteor.users.findOne(context.userId);
      }
    },
```

**Comment by yacomon** [comment]
I have the same problem

**Comment by SachaG** [comment]
Same here.

**Comment by lorensr** [comment]
Error is:

```
W20161101-12:25:20.552(-4)? (STDERR) TypeError: Cannot read property 'userId' of undefined
W20161101-12:25:20.553(-4)? (STDERR)     at user$ (imports/api/schema.js:28:11)
```

Goes away when you register/log in. It would be fixed by `= {}`:

`async user(root, args, context = {}) {`

but perhaps a better solution would be for apollo server to always give an object for `context`? @helfer 

http://dev.apollodata.com/tools/graphql-tools/resolvers.html#Resolver-function-signature
http://dev.apollodata.com/tools/graphql-server/setup.html#graphqlOptions

**Comment by SachaG** [comment]
Is there a reason why only `userId` is stored on the context instead of the full user object? It feels like it would just lead to a lot of duplicated code and extra db calls as you need to call `Meteor.users.findOne(userId)` in every resolver?

**Comment by lorensr** [comment]
That would be nice! Would accept pr that added context.user

**Comment by lorensr** [comment]
`context.user` added in 0.2.0

**Comment by SachaG** [comment]
That's awesome :)

**Comment by traa** [comment]
@lorensr when we're creating a server

```javascript
createApolloServer({
    schema,
});
```

`context` is still `undefined`. Do we need to set it somehow explicitly?

**Comment by lorensr** [comment]
Context always at least `{}` as of apollo@0.2.1 (https://github.com/apollostack/meteor-integration/pull/55)
