### ISSUE TITLE
userId undefined error on startup

### ISSUE THREAD

**Issue by deanius** [apollostack/meteor-starter-kit#41]
W20161203-21:46:50.694(-6)? (STDERR) TypeError: Cannot read property 'userId' of undefined
W20161203-21:46:50.755(-6)? (STDERR)     at user (imports/api/schema.js:29:11)
W20161203-21:46:50.755(-6)? (STDERR)     at resolveOrError (/Users/deanius/src/meteor-starter-kit/node_modules/graphql/execution/execute.js:454:12)

**Comment by lorensr** [comment]
Thanks for reporting, fixed by https://github.com/apollostack/meteor-integration/pull/55
